[build]
command = "cd nextjs && npm install && npm run build"
publish = "nextjs/.next"

[build.environment]
NEXT_TELEMETRY_DISABLED = "1"
NODE_VERSION = "18"
NPM_VERSION = "9"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[headers]]
for = "/*"
[headers.values]
Strict-Transport-Security = "max-age=31536000; includeSubDomains"
X-Frame-Options = "ALLOW-FROM https://t.me/ https://web.telegram.org https://runconnect.app"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "default-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com https://api.runconnect.app https://*.telegram.org https://cdnjs.cloudflare.com https://runconnect.app; connect-src 'self' http://localhost:8080 https://api.runconnect.app https://runconnect.app; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data:; font-src 'self' https://fonts.gstatic.com; frame-ancestors https://t.me/ https://web.telegram.org https://runconnect.app; script-src 'self' 'unsafe-inline' https://*.telegram.org https://cdnjs.cloudflare.com https://runconnect.app;"

[[redirects]]
from = "/webapp/*"
to = "/webapp/:splat"
status = 200
force = true

# Редирект с HTTP на HTTPS
[[redirects]]
from = "http://*"
to = "https://:splat"
status = 301
force = true

# Проксирование API запросов
[[redirects]]
from = "/api/*"
to = "https://api.runconnect.app/api/:splat"
status = 200
force = true
headers = {X-From = "Netlify", Access-Control-Allow-Origin = "https://runconnect.app", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Authorization, Content-Type, Accept, X-Request-ID", Access-Control-Allow-Credentials = "true"}

# Редирект для API с HTTP на HTTPS
[[redirects]]
from = "http://api.runconnect.app/api/*"
to = "https://api.runconnect.app/api/:splat"
status = 301
force = true

# Обработка SPA роутинга
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false
