[build]
publish = "public"

[[headers]]
for = "/*"
[headers.values]
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "default-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com https://api.runconnect.app https://*.telegram.org https://cdnjs.cloudflare.com https://runconnect.app; connect-src 'self' http://localhost:8080 https://api.runconnect.app https://runconnect.app; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data:; font-src 'self' https://fonts.gstatic.com; frame-ancestors https://t.me/ https://web.telegram.org https://runconnect.app; script-src 'self' 'unsafe-inline' https://*.telegram.org https://cdnjs.cloudflare.com https://runconnect.app;"
X-Frame-Options = "ALLOW-FROM https://t.me/"
Access-Control-Allow-Origin = "https://api.runconnect.app"
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
Access-Control-Allow-Credentials = "true"
Access-Control-Max-Age = "86400"

[[redirects]]
from = "/webapp/*"
to = "/webapp/index.html"
status = 200 