[build]
publish = "public"
command = ""

[[headers]]
for = "/*"
[headers.values]
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "default-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com https://api.runconnect.app https://*.telegram.org https://cdnjs.cloudflare.com https://runconnect.app; connect-src 'self' http://localhost:8080 https://api.runconnect.app https://runconnect.app; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data:; font-src 'self' https://fonts.gstatic.com; frame-ancestors https://t.me/ https://web.telegram.org https://runconnect.app; script-src 'self' 'unsafe-inline' https://*.telegram.org https://cdnjs.cloudflare.com https://runconnect.app;"
X-Frame-Options = "ALLOW-FROM https://t.me/"

[[redirects]]
from = "/webapp/*"
to = "/webapp/index.html"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 404 