[build]
publish = "dist"
command = "mkdir -p dist && npm run build"

[[headers]]
for = "/*"
[headers.values]
Strict-Transport-Security = "max-age=31536000; includeSubDomains"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Обработка статических файлов
[[redirects]]
from = "/static/*"
to = "/static/:splat"
status = 200
force = true

# Редирект с HTTP на HTTPS
[[redirects]]
from = "http://*"
to = "https://:splat"
status = 301
force = true

# Проксирование API запросов
[[redirects]]
from = "/api/*"
to = "https://api.runconnect.app/api/:splat"
status = 200
force = true
headers = {X-From = "Netlify", Access-Control-Allow-Origin = "https://runconnect.app", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Authorization, Content-Type, Accept, X-Request-ID, Origin", Access-Control-Allow-Credentials = "true", Access-Control-Max-Age = "86400"}

# Редирект для API с HTTP на HTTPS
[[redirects]]
from = "http://api.runconnect.app/api/*"
to = "https://api.runconnect.app/api/:splat"
status = 301
force = true

# Обработка SPA роутинга
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false

[build.environment]
NODE_VERSION = "18"
NPM_VERSION = "9" 