[build]
builder = "nixpacks"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
startCommand = "uvicorn api_app:app --host 0.0.0.0 --port $PORT"

[deploy.pre]
command = "alembic upgrade head" 