[build]
builder = "nixpacks"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/"
healthcheckTimeout = 100

[deploy.web]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100

[deploy.bot]
startCommand = "python main.py"
healthcheckPath = "/"
healthcheckTimeout = 100 