[build]
  base = "nextjs"
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "false"
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NEXT_PRIVATE_STANDALONE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "frame-ancestors 'none'"

# Разрешаем Next.js самому обрабатывать маршруты
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true 