[build]
  base = "nextjs"
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_FORCE_EDGE_IMAGES = "true"
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_ENV = "production"
  SKIP_INSTALL_DEPS = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "frame-ancestors 'none'"

# Обработка всех маршрутов через Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200
  force = true 